version: '3.8'

services:
  user-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.userApp
    image: user-app-image
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgresql://postgres:secret@db:5432/postgres
      - JWT_SECRET=secret
   
    container_name: user-app-container

  merchant-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.merchantApp
    image: merchant-app-image
    ports:
      - "3002:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgresql://postgres:secret@db:5432/postgres
      - JWT_SECRET=secret
    
  
    container_name: merchant-app-container

  bank-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.devBank
    image: bank-app-image
    ports:
      - "3003:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgresql://postgres:secret@db:5432/postgres
      - JWT_SECRET=secret
   
    container_name: bank-app-container

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
