name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            vishawdeepsingh602/user-app:latest
            vishawdeepsingh602/merchant-app:latest
            vishawdeepsingh602/bank-app:latest
          file: |
            ./docker/Dockerfile.userApp
            ./docker/Dockerfile.merchantApp
            ./docker/Dockerfile.devBank

      - name: Verify Pushed Images
        run: |
          docker pull vishawdeepsingh602/user-app:latest
          docker pull vishawdeepsingh602/merchant-app:latest
          docker pull vishawdeepsingh602/bank-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Stop and remove existing containers
            sudo docker stop user-app || true
            sudo docker rm user-app || true
            sudo docker stop merchant-app || true
            sudo docker rm merchant-app || true
            sudo docker stop bank-app || true
            sudo docker rm bank-app || true

            # Pull latest images
            sudo docker pull vishawdeepsingh602/user-app:latest
            sudo docker pull vishawdeepsingh602/merchant-app:latest
            sudo docker pull vishawdeepsingh602/bank-app:latest

            # Create a Docker network
            sudo docker network create my-network || true

            # Run containers
            sudo docker run -d --name user-app \
                             --network my-network \
                             -e DATABASE_URL=${{ secrets.DB_URL }} \
                             -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                             -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
                             -p 3001:3000 \
                             vishawdeepsingh602/user-app:latest

            sudo docker run -d --name merchant-app \
                             --network my-network \
                             -e DATABASE_URL=${{ secrets.DB_URL }} \
                             -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                             -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL2 }} \
                             -e GOOGLE_ID=${{ secrets.GOOGLE_ID }} \
                             -e GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }} \
                             -p 3002:3000 \
                             vishawdeepsingh602/merchant-app:latest

            sudo docker run -d --name bank-app \
                             --network my-network \
                             -e DATABASE_URL=${{ secrets.DB_URL }} \
                             -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                             -p 3003:3000 \
                             vishawdeepsingh602/bank-app:latest
