name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker build -f ./docker/Dockerfile.userApp -t vishawdeepsingh602/user-app:latest .
          docker build -f ./docker/Dockerfile.merchantApp -t vishawdeepsingh602/merchant-app:latest .
          docker build -f ./docker/Dockerfile.devBank -t vishawdeepsingh602/bank-app:latest .

      - name: Push Docker images
        run: |
          docker push vishawdeepsingh602/user-app:latest
          docker push vishawdeepsingh602/merchant-app:latest
          docker push vishawdeepsingh602/bank-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker stop user-app || true
            sudo docker rm user-app || true
            sudo docker stop merchant-app || true
            sudo docker rm merchant-app || true
            sudo docker stop bank-app || true
            sudo docker rm bank-app || true

            sudo docker rmi vishawdeepsingh602/user-app:latest || true
            sudo docker rmi vishawdeepsingh602/merchant-app:latest || true
            sudo docker rmi vishawdeepsingh602/bank-app:latest || true
            sudo docker pull vishawdeepsingh602/user-app:latest
            sudo docker pull vishawdeepsingh602/merchant-app:latest
            sudo docker pull vishawdeepsingh602/bank-app:latest
            sudo docker network create my-network || true

            sudo docker run  -e DATABASE_URL=${{ secrets.DB_URL }} \
                             -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                             -e NODE_ENV=${{secrets.NODE_ENV}} \
                             -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
                             -d --name user-app \
                             --network my-network \
                             -p 3001:3000 \
                             vishawdeepsingh602/user-app:latest

            sudo docker run  -e DATABASE_URL=${{ secrets.DB_URL }} \
                             -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                             -e NODE_ENV=${{secrets.NODE_ENV}} \
                             -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL2 }} \
                             -e GOOGLE_ID=${{ secrets.GOOGLE_ID }} \
                             -e GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }} \
                             -d --name merchant-app \
                             --network my-network \
                             -p 3002:3000 \
                             vishawdeepsingh602/merchant-app:latest

            sudo docker run -e DATABASE_URL=${{ secrets.DB_URL }} \
                             -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
                             -d --name bank-app \
                             --network my-network \
                             -p 3003:3000 \
                             vishawdeepsingh602/bank-app:latest
